name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'

      - name: Build with Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/githubactionsdemojava .

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v7
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/githubactionsdemojava
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

