name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'

      - name: Build with Maven
        run: mvn clean package

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v7
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/github-actions-demo-0.0.1
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Deploy to Remote Server
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout docker compose files

      - uses: humbertocrispim/ssh-docker-compose-action@v1.0.0
        name: Remote Deployment with Docker-Compose
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          pull: true # Update images when pulling
          script: |
            sudo docker-compose down
            sudo docker-compose up -d
