name: Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '21', '25' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'
      - run: java --version

      - name: Build and run tests
        run: mvn clean test

      - name: Generate test report
        run: mvn surefire-report:report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-reports-java-${{ matrix.java-version }}
          path: target/surefire-reports/
